cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://github.com/rayantx
spring:
  application:
    name: rest-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-springboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show_sql: true
    open-in-view: false
logging:
  level:
    root: info
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true